RUN install2.r --error --skipinstalled \ 
  afex \ 
  apaTables \ 
  BayesFactor \ 
  bayestestR \ 
  corrplot \ 
  cowplot \ 
  devtools \ 
  dplyr \ 
  emmeans \ 
  ggplot2 \ 
  ggpubr \ 
  ggthemes \ 
  glmnet \ 
  intmed \ 
  janitor \ 
  JWileymisc \ 
  kableExtra \ 
  knitr \ 
  lspline \ 
  MBESS \ 
  optimx \ 
  rlist \ 
  Rmisc \ 
  sjPlot \ 
  stringr \ 
  tidyr \ 
  tinylabels \ 
  XML
RUN installGithub.r \ 
  aaronpeikert/repro@adb5fa569 \ 
  crsh/papaja@devel
