# Generated by repro: do not edit by hand
# Please edit Dockerfiles in .repro/
FROM rocker/verse:4.0.1
ENV DEBIAN_FRONTEND=noninteractive
ARG BUILD_DATE=2020-12-10
WORKDIR /home/rstudio
RUN MRAN=https://mran.microsoft.com/snapshot/${BUILD_DATE} \
  && echo MRAN=$MRAN >> /etc/environment \
  && export MRAN=$MRAN \
  && echo "options(repos = c(CRAN='$MRAN'), download.file.method = 'libcurl')" >> /usr/local/lib/R/etc/Rprofile.site
RUN apt-get update -y && apt-get install -y octave gnuplot libgsl0-dev
RUN install2.r --error --skipinstalled \ 
  afex \ 
  apaTables \ 
  BayesFactor \ 
  bayestestR \ 
  car \ 
  devtools \ 
  dplyr \ 
  effectsize \ 
  emmeans \ 
  ez \ 
  ggplot2 \ 
  ggpubr \ 
  gridExtra \ 
  Hmisc \ 
  janitor \ 
  kableExtra \ 
  knitr \ 
  lspline \ 
  MBESS \ 
  misty \ 
  parallel \ 
  plotrix \ 
  plyr \ 
  reshape \ 
  rlist \ 
  Rmisc \ 
  sjPlot \ 
  tidyr \ 
  tinylabels \ 
  XML \
  optimx
RUN installGithub.r \ 
  aaronpeikert/repro@adb5fa569 \
  crsh/papaja@devel
