# Generated by repro: do not edit by hand
# Please edit Dockerfiles in .repro/
FROM rocker/verse:4.0.1
ARG BUILD_DATE=2020-12-10
ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /home/rstudio
RUN MRAN=https://mran.microsoft.com/snapshot/${BUILD_DATE} \
  && echo MRAN=$MRAN >> /etc/environment \
  && export MRAN=$MRAN \
  && echo "options(repos = c(CRAN='$MRAN'), download.file.method = 'libcurl')" >> /usr/local/lib/R/etc/Rprofile.site
RUN apt-get update -y && apt-get install -y libgsl0-dev
RUN install2.r --error --skipinstalled \ 
  afex \ 
  apaTables \ 
  BayesFactor \ 
  bayestestR \ 
  corrplot \ 
  cowplot \ 
  devtools \ 
  dplyr \ 
  emmeans \ 
  ggplot2 \ 
  ggpubr \ 
  ggthemes \ 
  glmnet \ 
  intmed \ 
  janitor \ 
  JWileymisc \ 
  kableExtra \ 
  knitr \ 
  lspline \ 
  MBESS \ 
  optimx \ 
  rlist \ 
  Rmisc \ 
  sjPlot \ 
  stringr \ 
  tidyr \ 
  tinylabels \ 
  XML
RUN installGithub.r \ 
  aaronpeikert/repro@adb5fa569 \ 
  crsh/papaja@devel
